# Use postgres/example user/password credentials
version: '2'

services:

  db:
    image: postgres
    restart: always
    environment:
       POSTGRES_USER: runed
       POSTGRES_PASSWORD: 123
    volumes:
       - ./db/runeterra.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8087:8080
  
  back:
    build: ./server
    ports:
      - 5000:5000
      
      
